version: "3"

services:

  discovery-eureka:
    image: ecom/microservice-discovery-eureka
    restart: always
    ports:
      - "8761:8761"

  gateway-zuul:
    image: ecom/microservice-gateway-zuul
    restart: always
    ports:
      - "8902:8902"

  product-service:
    image: ecom/microservice.product.service
    environment:
      DATABASE_HOST: mysql-product
      DATABASE_PORT: 3306
      DATABASE_NAME: msproduct
      DATABASE_USER: msecom
      DATABASE_PASSWORD: msecom
    restart: always
    ports:
      - "8002-8099:8002"
    depends_on:
      - mysql-product

  mysql-product:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: msproduct
      MYSQL_USER: msecom
      MYSQL_PASSWORD: msecom
    ports:
      - "3306:3306"

  customer-service:
    image: ecom/microservice.customer.service
    environment:
      DATABASE_HOST: mysql-customer
      DATABASE_PORT: 3306
      DATABASE_NAME: mscustomer
      DATABASE_USER: msecom
      DATABASE_PASSWORD: msecom
    restart: always
    ports:
      - "8102-8199:8102"
    depends_on:
      - mysql-customer

  mysql-customer:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mscustomer
      MYSQL_USER: msecom
      MYSQL_PASSWORD: msecom
    ports:
      - "3316:3306"

  order-service:
    image: ecom/microservice.order.service
    environment:
      DATABASE_HOST: mysql-order
      DATABASE_PORT: 3306
      DATABASE_NAME: msorder
      DATABASE_USER: msecom
      DATABASE_PASSWORD: msecom
    restart: always
    ports:
      - "8202-8299:8202"
    depends_on:
      - mysql-order

  mysql-order:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: msorder
      MYSQL_USER: msecom
      MYSQL_PASSWORD: msecom
    ports:
      - "3326:3306"

  ecommerce-storefront:
    image: ecom/ecommerce-storefront
    ports:
      - "9001:9001"