
server:
  port: 8761

eureka:
  instance:
    hostname: discovery-eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: container
eureka:
   client:
     serviceUrl:
       defaultZone: http://discovery-eureka:8761/eureka/