server:
  port: 8902
spring:
  application:
    name: microservice.gateway.zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true