# Use root/example as user/password credentials
version: "3"

services:

  config-server:
    image: ecom/microservice-config
    restart: always
    ports:
      - "9090:9090"

  discovery-eureka:
    image: ecom/microservice-discovery-eureka
    restart: always
    ports:
      - "8761:8761"

  product-service:
    image: ecom/microservice.product.service
    restart: always
    ports:
      - "8002-8099:8002"
    depends_on:
      - config-server
      - mysql-product

  mysql-product:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: msproduct
      MYSQL_USER: msecom
      MYSQL_PASSWORD: msecom
    ports:
      - "3306:3306"



    